server:
    port: ${PORT:8092}

spring:
    config:
        additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
    jpa:
        open-in-view: false
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        url: ${DATASOURCE_URL:jdbc:mysql://localhost:3308/park_info_sys}
        username: ${DATASOURCE_USER:user}
        password: ${DATASOURCE_PASS:password}
    rabbitmq:
        host: localhost
        port: 5672
        username: myuser
        password: mypassword
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8180/realms/techtopiaRealm/protocol/openid-connect/certs
                    issuer-uri: http://localhost:8180/realms/techtopiaRealm