
### Get all purchase orders
GET http://localhost:8091/purchase-orders

### Get all warehouse customers
GET http://localhost:8091/warehouse-customers

### Update purchase order
PATCH http://localhost:8091/purchase-orders/90131fe2-5770-4cdc-a830-1b1a7376346a
Content-Type: application/json

{
  "address": "hellostreet, 1",
  "deliveryDate": "2025-01-01T00:00:00",
  "orderStatus": "CREATED",
  "orderItems": []
}

### Create Fulfillment Order
POST http://localhost:8091/fulfillment-orders
Content-Type: application/json

{
    "purchaseOrderUUID": "ca693477-2146-4ef3-90f2-ada5b19a0338",
    "customerUUID": "c3d21b42-87b6-4c42-bf59-5a2fc2a6e0bd",
    "warehouseUUID": "7f12d1c5-9d4f-4c78-9156-3f5f32e3b68f",
    "orderNumber": "FO-2024-0001",
    "orderItems": [
        {
            "materialUUID": "4e96dcf3-b5de-4b6b-812e-9e23e6435a5e",
            "quantity": 10,
            "price": 34.5
        },
        {
            "materialUUID": "4e96dcf3-b5de-4b6b-812e-9e23e6435a5e",
            "quantity": 5,
            "price": 12.5
        }
    ]
}
