CREATE DATABASE IF NOT EXISTS invoicing;
GRANT ALL PRIVILEGES ON invoicing.* TO 'user'@'%';

CREATE DATABASE IF NOT EXISTS landside;
GRANT ALL PRIVILEGES ON landside.* TO 'user'@'%';

CREATE DATABASE IF NOT EXISTS waterside;
GRANT ALL PRIVILEGES ON waterside.* TO 'user'@'%';

CREATE DATABASE IF NOT EXISTS warehousing;
GRANT ALL PRIVILEGES ON warehousing.* TO 'user'@'%';
